#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
BOLD='\033[1m'

frontend=$1
mips=$2
current_dir=$(pwd)
test_count=0
fail_count=0

echo "==========================="
echo -e "Frontend used: ${YELLOW}$frontend${NC}"
echo "==========================="

for test_file in "$current_dir/tests/"*.in; do
    test_count=$((test_count + 1))
    base_name=$(basename "$test_file" .in)
    result_folder="$current_dir/tests/${base_name}_result"
    output_file="$result_folder/${base_name}.out"
    error_file="$result_folder/${base_name}.err"
    diff_file="$result_folder/${base_name}.diff"
    expect_file="$current_dir/tests/${base_name}.expect"

    mkdir -p "$result_folder"

    if [[ "$frontend" == "array" ]]; then
        register=$(head -n 1 "$test_file")
        padded_register=$(printf "%02d" $register)
        tail -n +2 "$test_file" > "${test_file}.tmp"
        /u/cs230/pub/$frontend "$mips" < "${test_file}.tmp" > "$output_file" 2> "$error_file"
        grep "\$${padded_register} =" "$error_file" | awk -v reg="$padded_register" '{for (i=1; i<=NF; i++) if ($i == "$"reg) {gsub("0x", "", $(i+2)); print strtonum("0x"$(i+2)); break}}' > "$output_file"
        rm "${test_file}.tmp"
    else
        /u/cs230/pub/$frontend "$mips" < "$test_file" > "$output_file" 2> "$error_file"
        if [[ "$frontend" == "arraydump" ]]; then
            grep -E "Array has size|Array element" "$error_file" | awk -F'[: ]+' '{print $NF}' > "$output_file"
        fi
    fi

    if diff -q "$output_file" "$expect_file" > /dev/null; then
        echo -e "${GREEN}${BOLD}Passed${NC}: ${base_name}"
        rm -r "$result_folder"
    else
        fail_count=$((fail_count + 1))
        diff --side-by-side "$expect_file" "$output_file" > "$diff_file"
        echo -e "${RED}${BOLD}Failed${NC}: ${base_name}"
        cat "$diff_file"
        echo ""
    fi

    echo "==========================="
done

echo -e "${GREEN}$((test_count - fail_count))/$test_count${NC} tests passed"
echo "==========================="
